language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="django==1.4.2,<1.5"
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django==1.9b1"
  - TOXENV=lint

matrix:
  exclude:
  - python: "3.2"
    env: DJANGO="django==1.4.2,<1.5"
  - python: "3.2"
    env: DJANGO="django==1.9b1"
  - python: "3.3"
    env: DJANGO="django==1.4.2,<1.5"
  - python: "3.3"
    env: DJANGO="django==1.9b1"
  - python: "3.4"
    env: DJANGO="django==1.4.2,<1.5"
  - python: "3.5"
    env: DJANGO="django==1.4.2,<1.5"
  - python: "3.5"
    env: DJANGO="django>=1.5,<1.6"
  - python: "3.5"
    env: DJANGO="django>=1.6,<1.7"
  - python: "3.5"
    env: DJANGO="django>=1.7,<1.8"
install:
  - "pip install $DJANGO"
script:
  - make travis
after_success:
  - coveralls
